### ISSUE TITLE
Project Team Changes Submitted 01/06 (Updated 12/06)

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/Support4Nurses#1]
Updated Changes with Clarifications:

### Landing page 
- [x] Please put the BU logo in the top left and NHS RBCH in top right
- [x] Menu section: overview –fine; categories – fine.  Could we have another button called Is this your concern? Then drop down menu with the scenario information (this info has been sent to Dave I believe).
- [x] The picture needs to be changed to a picture not the video please
- [x] What is support for nurses? Given the structure last line needs to say ‘You can use this button or click on the categories at the bottom of the page’
- [x] TRACS model; needs to be changed as there is a different TRAC model already out there.  So can the heading be changed from TRACS Model and definition to: Nurse retention resources: the TRACS approach
- [x] TRACS (lettering) please remove and just keep the boxes Transition etc with the definitions popping up when clicked
- [x] Why have the British flag as no other options?  Why have the thing next to it as takes you to something about Tribus???

### Begin your personalized journey link
The survey box is fine.  Then goes through to your results and reminds the person what they selected  – that’s fine.
- [x] The user then clicks on the tile not a separate button saying view resource. Ideally in time when clicking on the tile a short description of what is in there would be good. 
- [x] The date it was added needs to be there but hidden
    - Date hidden
- [x] The filter resources with resource type we should ditch as we just want people to be able to see them so doesn’t matter if on line or printable.  That means the whole screen would be available for the tiles

### Categories
Currently there is an errors as the user can’t see these. Nan explained to me how to get in hence my comments: 
- [x] When you get into the pages with the resources it doesn’t tell you what category you are in
    - **Janet confirmed resolved**
- [x] The information section filters don't work
    - **Identified issue, changes in method of displaying resources underway to resolve this**
- [x] Re above can this say information sections instead of resource category as we already have categories eg TRACs so makes it confusing
- [x] When you go into some resources, the link takes you out of the website and so when you click close you lose it – very frustrating.  Needs to be an obvious back button or some other solution: eg ‘Behaviours executive directors’
    - **Resolve by opening another tab for resources**
- [x] Please remove the resource type option
    - **Hidden**

### Out of Scope (Next Contract)
- [ ] The search button is very non-specific – how can we improve this eg try the term stress – brings up information about appraisal whereas I would expect something about support, self-help, wellbeing etc
- [ ] Transition etc: I think the project team needs to look in detail at what’s in each category and the label each has been given and get back to Dave as some things need moved and re labeled.   Lots of overlap between section content.
    - **Project team to provide prior to next phase**
- [ ] The images don’t work as they are all the same and don’t reflect the content.  Also they are very large meaning that when there are a lot of resources there is a lot of scrolling to see what there. 
    - I would prefer something colourful but more easily seen eg coloured tiles with one word labels about what the resource is.
- [ ] Resource categories career progression etc one is missing: Managing challenging situations.
    - **Added however, scoped for resources to be added once defined**

**Comment by davcpas1234** [comment]
### Original Feedback Provided
> This has now been updated in main thread above for progress tracking purposes

- [x] TRACS is still there and prominent
- [x] BU (Bournemouth University logo) needs to be added to the header
- [ ] Scenarios need to be added- add to top of page in wording- “Is this your concern”
- [x] “Happy” video on front page to be removed
- [x] add Managing Challenging situations category
- [x] adjust the word “category” to “information section”

**Clarification Points**
- [ ] different pictures; MH thought also not only have women in the childcare picture **SEE NOTE 1**
- [ ] More boxes on page- 9 boxes a page **SEE NOTE 2**
- [ ] Erase the word “printable” on the resources sections; MH thought maybe it could be called “downloadable” **SEE NOTE 3**
- [ ] Why is “resource type”  needed? **SEE NOTE 3**
- [ ] JS thought pages were empty- we shouldn’t have them all on one side **SEE NOTE 4**
- [ ] remove the word category from each page. **SEE NOTE 5**

**Comment by davcpas1234** [comment]
>Notes on above points:

1. different pictures; MH thought also not only have women in the childcare picture
    - **To be provided**
2. More boxes on page- 9 boxes a page
    - **There are 10 per page currently**
3. Why is “resource type”  needed?
    - **This was an initial idea to scope for different forms of resources (e.g. Departments/Contact Details) as opposed to pure documented resources** - Can be removed
4. JS thought pages were empty- we shouldn’t have them all on one side
    - **This needs to be clarified**
5. Remove the word category from each page
    - **The word "category" is referenced in many areas for different, this needs clarification**
