### ISSUE TITLE
Support4Nurses :: Tracker Ticket :: 21/01/2019

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/Support4Nurses#10]
_Transferred from Internal Tracker by Francis, Simone_

### Queries
- How are boxes/resources ordered in each category?
- Need for consistent spacing of boxes throughout the entire portal

#### Transition > Career progression
- [x] Nurse preceptorship portfolio and Preceptorship portfolio new is the same thing - delete the “Preceptorship portfolio new” **VCAS - Estimated at 5 mins**

#### Transition > Life Transition
- [x] Remove and Replace with NHS Pensions option within **VCAS - Estimated at 5 mins**

#### Resilience > Health and Wellbeing
- [x] Health and wellbeing info- type out Information (in all categories the word “info”  is used) **VCAS - Estimated at 15 mins**
- [x] Remove feel happy and keep feel happier. **VCAS - Estimated at 5 mins**
- [x] Add **Nursing You** https://www.c3health.org/our-programmes/health-professionals/nursing-you/ **VCAS - Estimated at 5 mins**
- [x] Add **Eight tips for eating well** https://www.nutrition.org.uk/healthyliving/healthydiet/8tips.html **VCAS - Estimated at 5 mins**

#### Authentic Leadership
- [x] Move “What is authentic leadership?” and “Authentic leadership in...” to top category **VCAS - Estimated at 5 mins**

#### Authentic Leadership > Appraisals
- [x] Rename “Preparing Conducting Appraisal Flow Chart” to "Preparing to conduct appraisal flow chart" **VCAS - Estimated at 5 mins**
- [x] Rename "How to upload appraisal records for all staff groups not doctors not consultants" to "How to upload appraisal records for all non-medical staff groups” **VCAS - Estimated at 5 mins**

#### Commitment > Care first
- [x] Put info box first **VCAS - Unable to Estimate**
#### Commitment > Pensions
- [x] Remove and Replace with NHS Pensions option within **VCAS - Estimated at 5 mins**

#### Support
- [x] Add **Diet and Nutrition** Subcategory with below external links: **VCAS - Estimated at 25 mins**
    - [x] **The Energy Diet** https://www.nhs.uk/live-well/sleep-and-tiredness/the-energy-diet/
    - [x] **What is a ‘healthy diet’?** https://www.nottingham.ac.uk/healthsciences/about/community/work-health-wellbeing/physical-health/diet-nutrition.aspx
    - [x] **Eight tips for healthy eating** https://www.nhs.uk/live-well/eat-well/eight-tips-for-healthy-eating/
    - [x] **Eating well** https://www.nhs.uk/live-well/eat-well/
    - [x] **Healthy eating outside of the home** https://www.nutrition.org.uk/healthyliving/outofhome.html 
- [x] Add **Nursing You** https://www.c3health.org/our-programmes/health-professionals/nursing-you/ **VCAS - Estimated at 5 mins**

**Comment by VersCreativeUKAutomate** [comment]
_Ticket updated with information from internal ticket by Popple, Amy_

**Comment by VersCreativeUKAutomate** [comment]
Estimation Summary:
- Estimated 16 tasks
- Unable to estimate 1 task

Total Time Estimation: **1hr 30mins**

**Comment by VersCreativeUKAutomate** [comment]
### Email Sent to Customer:

Dear <CUSTOMER>,

We have estimated for the request below:
- 4 x Change Requests
    - 8 x Resource Additions
    - 3 x Resource Renames
    - 2 x Resource Deletions
    - 4 x Resource Routing Changes


The above support requests have been estimated at **1 hour 30 minutes**. This support time carries a charge of **£55.00** based on your support agreement with us. This charge will be added to your **January** statement.

If you are happy to approve the above charge, please reply to this email to confirm your acceptance.

---

We have been unable to estimate the following requests:
- 1 x Change Request
    - We require additional information on the below request, please can you reply to this email with further information.

      > **Commitment**
      > **Care first**
      > Put info box first


**Please Note**: The above requests have not included in the estimate shown above. These requests require additional information and/or checks before being estimated. If you have any questions related to un-estimated changes please contact us. We will contact you with further information regarding the above un-estimated changes as soon as possible.

**Comment by VersCreativeUKAutomate** [comment]
Approval has been received from the customer to proceed with all estimated work.

**Comment by VersCreativeUKAutomate** [comment]
### Email Sent to Customer:
Dear ,

We have completed the below support requests and the changes are now live:

- 4 x Change Requests
    - 8 x Resource Additions
    - 3 x Resource Renames
    - 2 x Resource Deletions
    - 5 x Resource Routing Changes

We hope the changes suit your requirements, however if not please let us know.
