### ISSUE TITLE
Support4Nurses :: Tracker Ticket :: 24/01/2019

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/Support4Nurses#11]
_Transferred from Internal Tracker by Popple, Amy_

#### Transition
- [x] Training department - replace document **VCAS - Estimated at 5 mins**

#### Transition > Life Transitions
- [x] HR FAQ - replace document **VCAS - Estimated at 5 mins**
- [x] Childcare Nurseries replace with **Childcare and Family Friendly Workplace** **VCAS - Estimated at 5 mins**

#### Commitment
- [x] HR FAQ - replace document **VCAS - Estimated at 5 mins**
- [x] Health and Wellbeing links- remove document **VCAS - Estimated at 10 mins**

#### Resilience > Health and Wellbeing
- [x] Health and wellbeing A-Z page replace with **RBCH Health and Wellbeing** **VCAS - Estimated at 5 mins**
- [x] Health and Wellbeing information replace with **Tools for health and wellbeing** **VCAS - Estimated at 5 mins**

#### Resilience
- [x] Occupational Health services replace with **RBCH Occupational Health Services** **VCAS - Estimated at 5 mins**
- [x] Occupational Health main categories replace with **RBCH Occupational Health main categories** **VCAS - Estimated at 5 mins**

#### Support > Professional Development
- [x] Training department document - replace **VCAS - Estimated at 5 mins**

**Comment by VersCreativeUKAutomate** [comment]
_This ticket has 7 attachments_

**Comment by VersCreativeUKAutomate** [comment]
Estimation Summary:
- Estimated 10 tasks

Total Time Estimation: **55 mins**

**Comment by VersCreativeUKAutomate** [comment]
### Email Sent to Customer:

Dear <CUSTOMER>,

We have estimated for the request below:
- 2 x Change Request
    - 9 x Resource Update
    - 1 x Resource Deletions


The above support requests have been estimated at **55 minutes**. This support time carries a charge of **£27.50** based on your support agreement with us. This charge will be added to your **January** statement.

If you are happy to approve the above charge, please reply to this email to confirm your acceptance.

**Comment by VersCreativeUKAutomate** [comment]
Approval has been received from the customer to proceed with all estimated work.

**Comment by VersCreativeUKAutomate** [comment]
### Email Sent to Customer:
Dear <CUSTOMER>,

We have completed the below support requests and the changes are now live:

- 2 x Change Request
    - 9 x Resource Update
    - 1 x Resource Deletions

We hope the changes suit your requirements, however if not please let us know.
