### ISSUE TITLE
Project Team Changes - Submitted 18/06

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/Support4Nurses#2]
#### Category definitions
- [x] Commitment please change to ‘ Feeling valued within and by the organisation’
- [x] Support please change to ; Supporting healthy working lives’

#### Navigation Bar
- [x] Please move ‘is this your concern’ into the blue banner next to categories and add a drop down menu
- [x] Develop search facility

#### Is this your concern element
- [x] Take out the big blue section ‘is this your concern’ under photo as we want the TRACS areas to show up on page when opened and not to have to scroll down for these

#### Links to the scenarios
- [x] Link to relevant resources on click

#### Managing challenging situations 
- [x] Add resource from provided list

#### Resources
As mentioned we don’t like the pictures and they are too big. Instead we would like Tiles of colour (see below for an example, although no pictures wanted for ours) each with a very short title describing the resource.
 
![image](https://user-images.githubusercontent.com/3764587/41657719-266dfe50-748c-11e8-82b7-191917830a58.png)

- [x] Produce working model
- [x] Remove placeholder images
- [ ] _**Awaiting Feedback**_ Add additional resources _types_ provided

#### General points
- [x] Investigate issues with Internet Explorer
    - Major display issues identified on the home page and navigation due to flexbox support in IE11 - **RESOLVED**
    - Issues identified with modals not displaying due to Velocity compatibility and Issues in Bootstrap framework - **RESOLVED AND UPDATED** (respectively)
    - NOTE: This site **DOES NOT SUPPORT < IE10**. This is in line with official Microsoft support
- [x] Investigate issues with iPad responsivity
    - Minor issue with Category filters identified in Mobile and Tablet portrait view
    - No Further Issues identified
- [x] Go To Top button does not function
