### ISSUE TITLE
Project Team Changes :: Submitted 02/07

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/Support4Nurses#3]
### Resource Renames
- [x] Transition/career progression/Blended learning of theory skills experience and activity change to Nurse Preceptorship Bootcamp
- [x] Transition/life transitions/ temporary banking staff guidance change to Temporary staff guidance

### Resource Additions
- [ ] Transition/career progression then add a new section Career clinics (we will provide the resource in due course)
- [x] Transition/ life transitions then add a new section Bereavement

### External resources
- [x] https://www.youtube.com/watch?v=Jyy0ra2WcQQ Label to use for tile: Meditation and good sleep,under Resilience/Occupational Health/Health &  wellbeing
- [x] https://www.mind.org.uk/information-support/tips-for-everyday-living/relaxation/relaxation-exercises/#.WyYeGqlxlTY  Label to use for tile: Ways to relax,as above
- [x] https://www.nhsinform.scot/healthy-living/preventing-falls/fear-and-anxiety-about-falling/relaxation-techniques  Label to use for tile: Relax for health, as above plus Transition/learning/training
- [x] https://www.mindful.org/9-ways-mindfulness-reduces-stress/  Label to use for tile: Mindfulness and stress, under Resilience/Health & wellbing
- [x] https://www.happier.com/blog/25-ways-to-feel-happier-in-the-next-5-minutes/ Label to use for tile: Feeling happier,as above
- [x] https://www.wikihow.com/Feel-Happier Label to use for tile: Feel happy as above 
- [x] https://www.wikihow.com/Be-Assertive-Without-Being-Arrogant    Label to use for tile: Assertive and kind Authentic leadership/ new tile called Assertiveness
- [x] https://www.hee.nhs.uk/our-work/older-persons-fellowship   Label for tile: Older Persons’ Nursing Fellowship Transitions/career progression then new tile called educational fellowships
- [x] https://www.hee.nhs.uk/our-work/return-practice-nursing   Label for tile: Return to Nursing Practice Transitions/career progression then new tile called return to practice
- [x] https://www.leadershipacademy.nhs.uk/programmes/elizabeth-garrett-anderson-programme/  Label for tile: Leadership Programme for mid/senior level in Transitions/career progression then new tile called Leadership programmes; as well as Authentic leadership/leadership development  and new tile called Leadership programmes
- [x] https://www.leadershipacademy.nhs.uk/programmes/the-stepping-up-programme/ Label for tile: Stepping up for BAME aspiring leaders Transitions/career progression then new tile called Black Asian & Minority Ethic Leaders programmes; as well as in Authentic leadership/leadership development  and new tile called Black Asian & Minority Ethic Leaders
- [x] http://www.nhsemployers.org/your-workforce/plan/building-a-diverse-workforce/get-involved/the-mary-seacole-awards Label for tile: Leadership awards for minority ethnic health improvement Authentic leadership/leadership development  and new tile called Mary Seacole Awards
- [x] https://www1.bournemouth.ac.uk/study/continuing-professional-development-training/health-social-care-cpd/post-registration-health-social-care-professionals  Label for tile: Bmth Uni post-reg courses in support/ professional development/ new tile please

### Analytics
- [x] Add Analytics
    - We would like to know what parts of the site are being accessed - we discussed you providing this function; can I have an update please?

### Cross-Compatibility
Site works well on firefox and chrome but not on the BU version of explorer; I believe our version is too old from your feedback. 
- [x] Add incompatibility message for < IE11

![image](https://user-images.githubusercontent.com/3764587/42171128-6368c744-7e10-11e8-8935-34464daca4d3.png)

I was able to get it on my phone using chrome but the display was partial
It has to function well from a phone as this is likely to be the main way it is used.
One colleague looked at it on ipad and it didn't display properly but I haven't tried this.
- [ ] Investigate continuing issues on Mobile and Tablet

Stability
- [x] Continued issues with resource steering files
    - resilience/health and wellbeing - no resources showing **and**
    - resilience/care first health and wellbeing - no resources showing **and**

- [x] Back flow issues
    - Also when you are in a category eg transition then go into a sub category eg life transitions you can’t get back to transitions or others via the menu directly above but have to go to navbar.

- [x] Remove Swiper Arrows from index
