### ISSUE TITLE
Support4Nurses :: Tracker Ticket :: 07/08/2018

### ISSUE THREAD

**Issue by VCAmyPopple** [VersCreativeUK/Support4Nurses#6]
#### Tile Colour
- [x] Remove all white tiles from display
- Was previously resolved as part of a change request however, this has reverted.
- **Example failures:** `Resilience > Difficult Situations`, `Resilience > Health and Wellbeing`

#### Resource Naming
- [x] Change “Meeting Needs and Reducing Distress 1” to “Guidance on the Prevention and Management of Clinically related Challenging Behaviour”
- Under `Resilience > Difficult Situations` - this was previously requested
- [x] Change “Help Guides under Appraisal Policy Name” to "Appraisal Policy – help guide"
- [x] Replace "Appraisal Policy - help guide" `.docx` file with supplied `.pdf`

#### Search Accuracy
- [x] Users are reporting lack of return from specific keywords
- **Example failures:** `Union`, `bereavement`
- [x] Add resource location to search results to aid with duplication

#### Scenario Changes
- [x] Move "Support for Workplace Bullying".
- Move from "Health and Well-being" to "Managing Challenging Situations"
##### Adjust Scenario Steering files
- [x] Add files from `Resilience > Difficult Situations` to the following Scenario IDs:
- 27
- 28
- 29
- [x] Override files in Scenario ID 25 with files from Scenario ID 14

#### Personalised Questionnaire
- [x] Issue with Health & Well-Being not returning any results

#### Implementation
- [x] Add survey monkey link supplied to navigation

**Comment by VCAmyPopple** [comment]
Time to complete estimated at 1 hour.

**Comment by VCAmyPopple** [comment]
This will require additional estimation due to additional change submitted

**Comment by VCAmyPopple** [comment]
Time to complete estimated at 2 hours.
