### ISSUE TITLE
Support4Nurses :: Tracker Ticket :: 15/08/2018

### ISSUE THREAD

**Issue by VCAmyPopple** [VersCreativeUK/Support4Nurses#7]
#### Resource Changes
- [x] Move `Support4nurses Facebook Group` from `3_Authentic Leadership` to `5_Support`
- [x] Rename `Support4nurses Facebook Group` to `Support4nurses Facebook Group RBH Staff only`
- [x] Remove `Support > Union Contacts – South West` and all child resources
- [x] Add `Useful Phone Numbers for RBH Staff Only` resource to `5_Support`

#### Identified Bug
- [x] `links.json` is incorrectly displaying in Scenario resource steering results.
    - This has surfaced since the last change and was not identified during testing
    - Not part of support estimate

**Comment by VCAmyPopple** [comment]
Change estimated at 15 mins.

**Comment by VCAmyPopple** [comment]
`links.json` issue resolved with correction to `scenario-resource-list.html.inc.php`'s `mime_content_type` filter
