### ISSUE TITLE
Support4Nurses :: Tracker Ticket :: 18/08/2018

### ISSUE THREAD

**Issue by VCAmyPopple** [VersCreativeUK/Support4Nurses#9]
#### Transition:
- [x] Within Professional development- the repeated box named professional development- rename to Student and Mentor Support **VCAS - Estimated: 5mins**

#### Life Transition:
- [x] 	Bereavement box- change title to: Carefirst Bereavement: Practical advice  **VCAS - Estimated: 5mins**
- [x] 	HR and Flexible Working- Rename to HR and Flexible working FAQ  **VCAS - Estimated: 5mins**
- [x] 	Add Pensions box (use same resources as the Pensions in Commitment category)  **VCAS - Estimated: 15mins**

#### Resilience:

- [x] Difficult situations- bereavement repeated- change the box titled “Bereavement” to “Carefirst Bereavement: Practical advice” **VCAS - Estimated: 5mins**
- [x] Health and wellbeing: Mindfulness- make one box and then once you click on that box, you get all 3 sub-boxes (Mindfulness and Stress; Mind guide to Mindfulness; What is Mindfulness?)  **VCAS - Estimated: 15mins**
- [x] Rename the H & Wellbeing A-Z pg: Health and Wellbeing Services  **VCAS - Estimated: 5mins**
- [x] Occupational Health: Poorly displayed main categories and OH info  **VCAS - Error: Unable to estimate**
- [x] Rename “OH info”  to Occupational Health Services  **VCAS - Estimated: 5mins**

#### Commitment:
- [x] Most info needs being re-designed (boxes not matching up, different font sizes, weird spaces in between).  **VCAS - Error: Unable to estimate** 
- [ ] Change Carefirst to “Introduction to Carefirst”: put information and advice into this button  **VCAS - Estimated: 15mins**
- [x] HR info- rename to “HR FAQ”  **VCAS - Estimated: 5mins**

#### Support:
- [x] 	Professional development- needs to be renamed to “Student and Mentor Support”  **VCAS - Estimated: 5mins**

#### Others:
- [x] Buttons aren’t always placed in line with each other; looks messy  **VCAS - Error: Unable to estimate**
- [x] Make sure font sizes are consistent on the buttons, etc.  **VCAS - Estimated: 10mins**
- [x] On phone, tends to go back a page when scrolling to the next  **VCAS - Error: Unable to estimate**

**Comment by VersCreativeUKAutomate** [comment]
Summary:
- Estimated 11 Tasks
- Unable to estimate 4 Tasks

Total Time Estimation: **1hr 35mins**

**Comment by VersCreativeUKAutomate** [comment]
### Email Sent to Customer:

Dear <CUSTOMER>,

We have estimated for the request below:
- 4 x Change Requests
   - 8 x Resource Rename Requests
   - 1 x Resource Duplication
   - 5 x Resource Routing Changes
   - 1 x UI Change

The above support requests have been estimated at **1 hour 35 minutes**. This support time carries a charge of **£55.00** based on your support agreement with us. This charge will be added to your **November** statement.

If you are happy to approve the above charge, please reply to this email to confirm your acceptance.

---

We have been unable to estimate the following requests:
- 4 x Bug Reports
    - We are unable to estimate bug reports until investigations are complete.

**Please Note**: The above requests have not included in the estimate shown above. These requests require additional information and/or checks before being estimated. If you have any questions related to un-estimated changes please contact us. We will contact you with further information regarding the above un-estimated changes as soon as possible.

**Comment by VersCreativeUKAutomate** [comment]
Approval has been received from the customer to proceed with all **estimated** work.

**Comment by VersCreativeUKAutomate** [comment]
### Email Sent to Customer:

Dear ,
 
We have completed the below support requests and the changes are now live:
- 4 x Change Requests 
    - 8 x Resource Rename Requests
    - 1 x Resource Duplication
    - 5 x Resource Routing Changes
    - 1 x UI Change
 
We hope the changes suit your requirements, however if not please let us know.

**Comment by VCAmyPopple** [comment]
Email follow up sent to customer to clarify outstanding tasks.

**Comment by davcpas1234** [comment]
Executive Summary:

- Mobile device bugs:
    - Caused by resizing trigger on mobile devices where the `AddressBar` (iOS) / `ActionBar` (Android) is hidden dynamically.
- Occupational Health:
    - Rewrite being provided by the customer
- Button Spacing:
    - Design feature of Isotope layout defaults to `masonry`, replaced and redesigned to be be `fitRows`
